# Generated by Django 6.0.4 on 2026-04-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0004_alter_timetable_options_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable')},
        ),
    ]
